# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d2a8e080be8eb0f753c4e621d555e375e11ce2e479db76ad63977d857456a85cf3558907f8c8435059e44767706453ec34a75a2fde4c32d324082131f01a5b7

test:
  secret_key_base: 637f7d5cbb2993c3f5e6ac7be342099ff8055600c4441886459cc170f00d34499c983f7e39a1be28aa2b54db7bd0df8c5d28838125f2ea3e1e2644dc11436b4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
